### ISSUE TITLE
legal stuff

### ISSUE THREAD

**Issue by yuwui** [CramMK/marcmk.github.io#1]
hey, I noticed you used my site as a base for your own! while I don't mind people using my code as base for their own projects, I *did* notice you removed the original (AGPLv3) license, which is violating the terms of the license. If you could at least re-add that and maybe also mention me/the original repository somewhere that would be awesome!

**Comment by CramMK** [comment]
Hi, yeah sure I can add those! I'll do it tomorrow on my laptop, cause doing it on my windows pc is a headache :c
Should I add a mention to the repo only or also in the sourcefiles? Also thanks that you react so calmly, I should've asked first tbh.

**Comment by yuwui** [comment]
just a mention in the README is fine c:

**Comment by CramMK** [comment]
Added the license file, issue closed c:
